language: node_js
env:
  global:
  - secure: P5fnpcljh1RxKal2DdFqY25c9LcMCkEw3SwoKy9SikytBip+lAkAwfGRBjbQJz5NbZq6B6Wo8vK4huZCTlYyWw9RlYamTFvYqMntSeD5OjNFDYrsFMoGOXrkdc1VsljZsHANCRcHLKbZeGcmBDopbKAd87lICTwteHLqQ3EiV1iJIWJ78+Qqct8rjYWcQpxXsNBbYZ7+uWZmevNeUyAYwwMwdQpIMoKER1haNQ86rogDvV1A7rOHALGYv900/3uLkHkyR3liMTqAhe1B/IqvKii3jBqZ725A578weBVnd+oc2EM7Pasen75yCCx/TJivS77AmmksvYiMRyHueUIuPhnri90C5vZVgfVBtAw151Nxjg/lMHkri252R2v1p2IDUhuF5qrTZjAMBg4DyMU2h3U4tpnqmIzMRSjY7lt9xQI3UEId1xv1InB4u1OfkQnVYAPuzTA6ngNUBYw8+V9F0w30vvhZgIfCMNqmtPQCle9vHbPAsGjSfAgKxlF0MTx1OlO0sIAGaHsbWXcAyjmJ9X1p8LYN6q1VfM5AmNrfOvTgasml4FTDjU2u8tSS04WwabWUek90y6XSX2LORL5gTm1BTXmLw9wSgSgPvQ5+inhf9jb/c95REWt49TOdp1jgF6GyXV9nZnvEUZ9OkiAn+3AynKBHA3+n8rWmc9CSVgg=
  - secure: QeKZ0nBmVIGVRklch4btsmzus/8KyG7uhMgGI1y3pPYfx3AXMXOR1xHHaj3AC1n0nISb6upHMpK0Qi+1+qzfC5JtaK70jZl4YqNp7ixJWjF4zdSEI8Z3Sf1Xem4aS16s6g4syk6sau8M5CrC4hK+T4+GU9jC5DZQXS2egRbbmR8Ca/EO9OjU/0QROIuGmtb+EeSSwD+9TZMqmmaBce3SAfo04x3Nw0bLzcne56XaRkR5C0tvg/Gviz1Pre2TKKj32u0BUnWvkxZukzAXK+um90/l1AoN8kNNyV/xRKR5MwvCWlKN+lkVx1+1B2U+06ENnV31ApIZldiOYIUGBFZQEsv3znLQ/8o8A6+rAQ1gMELylTJGTYICbrWqedyhpWnAF2sy5SScY5RDiLHdE3JjUDaQbIlntqUdf3CF0cTMpcL26wofmkmybQwAz8Mn/J+ZdUccSou8UST922BZyJuA/0EzERvfwocWwJEm+SA8uEmisRQQ0t4cevzWUEcrxGvDA4FZ3cuCh8eoS/pC9/lig4FsVr1UU7ZqCcJko34MJ/WQQcqFno7w5GGato6tm5mINtmE8QjU6gu27QEhK0KIdGEXnJuqRJPmdgs8cfe/sg0wwLfqBPRfG4M1AyhzTmg1PMUa4+r8pn24s/eYl3wdWDSfiMuoQmKav4J9weH+cDU=

cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
jobs:
  include:
  - stage: github page
    if: "(type != pull_request) AND (branch = master)"
    script: npm run build
    node_js: '12'
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: "$GITHUB_TOKEN"
      local_dir: dist
      on:
        branch: master
