language: node_js

cache:
  directories:
  - node_modules

script:
- npm run build
- npm test

jobs:
  include:
  - stage: github page
    if: "(type != pull_request) AND (branch = master)"
    script: npm run build
    node_js: 'stable'
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: "$GITHUB_TOKEN"
      local_dir: dist
      on:
        branch: master
