language: node_js

env:
  global:
  - secure: c/uJXyI6WHuXyBDRNASvJHmWhRgA1WvGiKZNO/b6fD5TG4bi0xS+t54s/2FokdaUQupXLXVto4RlYOmKNCFB+8AwGUx570CJBYnypWj8qQ68dy0ShvSKFT+8eWYR9aoVu9EIwM3uownppxBAMGwgd0JOZGsLW1KY2LG0wiMlQGjyy+moa5lkOauKohOUV/pd4vTtRUyWx328es1JK26kzvrGppZlmYfbgGzU9oAzltz7eGPUU5iGkmsTsnno+j3A4luKjc15KKGiBIt+Zs9qaiSSmvVozVzMVuY2wWhdRnrbZfiBErZcQwqNB9xdBal+dR3wAeuCsUeMhsAfrVYWxyb6J6hAyKDZ2oO7M1Dt0BNlGvG7jwa1Tm8h/Rb24vdHoRwoRZs3R20gCZD1djMJaBnReyYKEqE9KgFsqmt6L6cheGNtkn5DH8ir2RVSVwGewA1ttbceS1H0cQ0kXz4m7izxqAt9WfgNiifnbvPlWqmWts/DT3411/YgfQlQfeJg19exWcUN3H4HfsZQCSQwTGgptF5tWe/HxKNxYrkfswT2qgnhH6fIlzOAnPcujlhKtlTtpEkc6Tvsf86DIe/QTBtQZpgE8xzfH1o8Up0ruOMs0pxPtd49mDWtREO5TC0Od0wvmp1XiNKYqIlX6jl03wc3fPr3Us/g1TW1ImguM94=
  - secure: LclPTzegpRE0cgi5hvbX0qXTQeO5DWjSInEnVVtAYGVDgC4elN/DTNGAS8gb+iUwX7ydokCilfYYGubfJ+o6+euQk7eHL0+4EH+ZjZKU2KMRZriu4B8fZx9zisJGWUESMk0FpBa5oWnZ9Vq3LjeAk71FRfpjpJgDNnxD6GMNil6HBVL6AZM91efq99U12aSs+85fGn7kEeTvmeGeIUPuDRfuJHSaJ7buIdBDha7qu8Q3m0ZSlRp9CvihVIbEKcDVGDJxcg8Tq7pzKXlIyM3MJc5tQHHZ3WKbyqKxxMRbccvd7OOpoR6VJqhVI8w4xjr83/F/vyWX3yLjUHq6Ncg5FSMF/0cgx0Qt2tmqXHpDv77ZfUtav7Ot5Ru7VszN5dORdCzbToeEvoIX9T32XOcC/YLlDJq3dyAWTnj6u1KEPHJmGo9NlxdF9lXHxEJTbR2u37EVTADGbVbE5FZ7+KUst7rYwdxR/yn9+IIyy/tL/DnyW7SHDi9SRJA6d37iyuC2LUwHfz95Iy4/dsb6FwM38cWMCJJOsiPXCsmElWb97USeGfC3hMvkyKcUYSJdxJUC+P0Z/O7ou8WSohFacVxqkha5a52VPG1YYzGCKePLV08PfE1a1b/c+0dgyHrUHFVDV1mgOlCFHJvB2SIp0/cUASPtnPt9vCV7d1rdOCT37W4=

cache:
  directories:
  - node_modules

script:
- npm run build
- npm test

jobs:
  include:
  - stage: github page
    if: "(type != pull_request) AND (branch = master)"
    script: npm run build
    node_js: '12'
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: "$GITHUB_TOKEN"
      local_dir: dist
      on:
        branch: master
